import Mock from 'mockjs';

const dataSetLovTemple = {
  'content|10': [
    {
      _token: '@guid()',
      'objectVersionNumber|1-10': 1,
      code: "@pick(['HR', 'SYS']).@upper(@word)",
      'codeId|+1': 10001,
      codeValues: '@ctitle()',
      description: '@ctitle()',
      type: '@name',
      enabledFlag: /[NY]/,
      parentCodeId: [/1[0-9]{10}/, /1[0-9]{10}/],
      parentCodeDescription: '@sentence(3, 6)',
    },
  ],
  success: true,
  totalElements: 35,
};
const lovDefineTemple = {
  _token: '@guid()',
  objectVersionNumber: 1,
  code: 'LOV_CODE',
  description: '快码',
  height: 300,
  lovId: 10015,
  lovItems: [
    {
      _token: '@guid()',
      objectVersionNumber: 1,
      lovItemId: 10033,
      lovId: 10015,
      display: '代码',
      gridFieldName: 'code',
      gridFieldWidth: 150,
      gridFieldAlign: 'left',
      autocompleteField: 'Y',
      conditionField: 'Y',
      isAutocomplete: 'N',
      gridField: 'Y',
      conditionFieldWidth: null,
      conditionFieldLabelWidth: null,
      conditionFieldType: null,
      conditionFieldName: null,
      conditionFieldTextfield: null,
      conditionFieldNewline: 'N',
      conditionFieldSelectUrl: null,
      conditionFieldSelectVf: null,
      conditionFieldSelectTf: null,
      conditionFieldSelectCode: null,
      conditionFieldLovCode: null,
      conditionFieldSequence: 1,
      gridFieldSequence: 1,
    },
    {
      _token: '@guid()',
      objectVersionNumber: 1,
      lovItemId: 10034,
      lovId: 10015,
      display: '描述',
      gridFieldName: 'description',
      gridFieldWidth: 250,
      gridFieldAlign: 'left',
      autocompleteField: 'Y',
      conditionField: 'Y',
      isAutocomplete: 'N',
      gridField: 'Y',
      conditionFieldWidth: null,
      conditionFieldLabelWidth: null,
      conditionFieldType: null,
      conditionFieldName: null,
      conditionFieldTextfield: null,
      conditionFieldNewline: 'N',
      conditionFieldSelectUrl: null,
      conditionFieldSelectVf: null,
      conditionFieldSelectTf: null,
      conditionFieldSelectCode: null,
      conditionFieldLovCode: null,
      conditionFieldSequence: 2,
      gridFieldSequence: 2,
    },
  ],
  placeholder: '请选择快码',
  sqlId: 'CodeMapper.select',
  customSql: null,
  queryColumns: 1,
  customUrl: null,
  textField: 'description',
  title: '父级快码',
  valueField: 'code',
  width: 500,
  delayLoad: 'N',
  needQueryParam: 'N',
  editableFlag: 'Y',
  canPopup: 'Y',
  lovPageSize: '10',
  treeFlag: 'N',
  idField: null,
  parentIdField: null,
};
const d1 = {
  content: [
    {
      objectVersionNumber: 1,
      codeId: 10001,
      codeValueId: 10029,
      description: null,
      meaning: '老',
      value: 'O',
      orderSeq: 10,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: null,
      parentCodeValue: null,
      parentCodeValueMeaning: null,
    },
    {
      objectVersionNumber: 1,
      codeId: 10001,
      codeValueId: 10030,
      description: null,
      meaning: '少',
      value: 'Y',
      orderSeq: 20,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: null,
      parentCodeValue: null,
      parentCodeValueMeaning: null,
    },
  ],
};
const d2 = {
  content: [
    {
      objectVersionNumber: 1,
      codeId: 10001,
      codeValueId: 10027,
      description: null,
      meaning: '女',
      value: 'F',
      orderSeq: 10,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: null,
      parentCodeValue: null,
      parentCodeValueMeaning: null,
    },
    {
      objectVersionNumber: 1,
      codeId: 10001,
      codeValueId: 10028,
      description: null,
      meaning: '男',
      value: 'M',
      orderSeq: 20,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: null,
      parentCodeValue: null,
      parentCodeValueMeaning: null,
    },
  ],
};
const d3 = {
  content: [
    {
      objectVersionNumber: 1,
      codeId: 10010,
      codeValueId: 10021,
      description: '有效',
      meaning: '有效',
      value: 'ACTV',
      orderSeq: 10,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: null,
      parentCodeValue: null,
      parentCodeValueMeaning: null,
    },
    {
      objectVersionNumber: 1,
      codeId: 10010,
      codeValueId: 10022,
      description: '过期',
      meaning: '过期',
      value: 'EXPR',
      orderSeq: 10,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: null,
      parentCodeValue: null,
      parentCodeValueMeaning: null,
    },
    {
      objectVersionNumber: 1,
      codeId: 10010,
      codeValueId: 10023,
      description: '锁定',
      meaning: '已锁定',
      value: 'LOCK',
      orderSeq: 10,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: null,
      parentCodeValue: null,
      parentCodeValueMeaning: null,
    },
  ],
};
const d4 = {
  content: [
    {
      _token: '0ac5c3561d43fb2755532be093e2b5f2',
      objectVersionNumber: 1,
      codeId: 10066,
      codeValueId: 10206,
      description: '北京',
      meaning: '北京',
      value: 'BJ',
      orderSeq: 10,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: null,
      parentCodeValue: null,
      parentCodeValueMeaning: null,
    },
    {
      _token: 'b205b085ad8457370f571330f83b13cf',
      objectVersionNumber: 1,
      codeId: 10066,
      codeValueId: 10207,
      description: '上海',
      meaning: '上海',
      value: 'SH',
      orderSeq: 10,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: null,
      parentCodeValue: null,
      parentCodeValueMeaning: null,
    },
  ],
};
const d5 = {
  content: [
    {
      _token: '383aa9f02290742d77bbb1200be8a95e',
      objectVersionNumber: 2,
      codeId: 10067,
      codeValueId: 10204,
      description: '青浦区',
      meaning: '青浦区',
      value: 'QP',
      orderSeq: null,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: 10207,
      parentCodeValue: 'SH',
      parentCodeValueMeaning: null,
    },
    {
      _token: '68db92966e875bdd16a9d38ef27e90d8',
      objectVersionNumber: 2,
      codeId: 10067,
      codeValueId: 10205,
      description: '徐汇区',
      meaning: '徐汇区',
      value: 'XH',
      orderSeq: null,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: 10207,
      parentCodeValue: 'SH',
      parentCodeValueMeaning: null,
    },
    {
      _token: '380ee41f753c1aa563dfdc48aded0309',
      objectVersionNumber: 1,
      codeId: 10067,
      codeValueId: 10208,
      description: '海定区',
      meaning: '海定区',
      value: 'HD',
      orderSeq: 10,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: 10206,
      parentCodeValue: 'BJ',
      parentCodeValueMeaning: null,
    },
    {
      _token: 'f5167255b276b5cdd677d175eee0a121',
      objectVersionNumber: 1,
      codeId: 10067,
      codeValueId: 10209,
      description: '朝阳区',
      meaning: '朝阳区',
      value: 'CY',
      orderSeq: 10,
      tag: null,
      enabledFlag: 'Y',
      parentCodeValueId: 10206,
      parentCodeValue: 'BJ',
      parentCodeValueMeaning: null,
    },
  ],
};
const d6 = {
  'HR.EMPLOYEE_GENDER': d2.content,
  'SYS.USER_STATUS': d3.content,
  SHENG: d4.content,
  SHI: d5.content,
};
const dsMutationsT = {
  content: [],
  totalElements: 1000,
  success: '@boolean()',
};
const dsQueriesT = {
  'content|10': [
    {
      userid: '@guid()',
      'age|18-100': 34,
      name: '@cname()',
      code_description: '员工状态',
      code_code: 'HR.EMPLOYEE_STATUS',
      code_select: 'HR.EMPLOYEE_GENDER',
      codeMultiple_description: '@last(),@last()',
      codeMultiple_code: [/1[0-9]{10}/, /1[0-9]{10}/],
      sex: /[MF]/,
      'sexMultiple|1-2': [/[MF]/],
      account: {
        multiple: /M|F|M,F|F,M/,
      },
      enable: '@boolean()',
      frozen: /[NY]/,
      date: {
        startDate: null,
        endDate: null,
      },
      other: {
        'enemy|3': [
          {
            userid: '@guid()',
            'age|18-100': 34,
            name: '@cname()',
            sex: /[MF]/,
            'friends|3': [
              {
                userid: '@guid()',
                'age|18-100': 34,
                name: '@cname()',
                sex: /[MF]/,
              },
            ],
          },
        ],
      },
    },
  ],
  totalElements: 1000,
  success: true,
};
const dsLanguagesT = {
  content: [
    {
      name: {
        zh_CN: '@cname()',
        en_GB: '@name()',
        en_US: '@name()',
        ja_JP: '桥本@clast()',
      },
      'first-name': {
        zh_CN: '@cname()',
        en_GB: '@name()',
        en_US: '@name()',
        ja_JP: '本田@clast()',
      },
    },
  ],
  totalElements: 1,
  success: true,
};
const dsValidateT = [true];
const dsMutationsD = Mock.mock(dsMutationsT);
const dsQueriesD = Mock.mock(dsQueriesT);
const dsLanguagesD = Mock.mock(dsLanguagesT);
const dsValidateD = Mock.mock(dsValidateT);
const data1 = Mock.mock(d1);
const data2 = Mock.mock(d2);
const data3 = Mock.mock(d3);
const data4 = Mock.mock(d4);
const data5 = Mock.mock(d5);
const data6 = Mock.mock(d6);
const lovTempleData = Mock.mock(dataSetLovTemple);
const lovDefineData = Mock.mock(lovDefineTemple);
export default {
  'POST /_api/table/inline/common/lov/dataset/LOV_CODE': lovTempleData,
  'POST /_api/table/inline/sys/lov/lov_define': lovDefineData,
  'POST /_api/table/inline/common/code/HR.EMPLOYEE_GENDER/?key': data1,
  'GET /_api/table/inline/common/code/HR.EMPLOYEE_GENDER': data2,
  'POST /_api/table/inline/common/code/SYS.USER_STATUS': data3,
  'POST /_api/table/inline/common/code/SHENG': data4,
  'POST /_api/table/inline/common/code/SHI': data5,
  'POST /_api/table/inline/common/batch': data6,
  'POST /_api/table/inline/dataset/user/mutations': dsMutationsD,
  'POST /_api/table/inline/dataset/user/queries': dsQueriesD,
  'POST /_api/table/inline/dataset/user/languages': dsLanguagesD,
  'POST /_api/table/inline/dataset/user/validate': dsValidateD,
};
